# Разработчик: Soldi_n
# Плагин: SoldinWorldBlock
# Версия: 1.0

worlds:
  nether:
    display: "Ад"
    enabled: true
  end:
    display: "Эндер"
    enabled: true

messages:
  block:
    start: "Мир {world} закрыт на {time}!"
    countdown:
      3600: "Мир {world} будет открыт через 1 час!"
      1800: "Мир {world} будет открыт через 30 минут!"
      60: "Мир {world} будет открыт через 1 минуту!"
      10: "Мир {world} будет открыт через 10 секунд!"
    opened: "Мир {world} открыт!"
  unblock: "Мир {world} теперь открыт!"
  blocked_portal: "Мир еще не открыт!"
