name: Build SoldinWorldBlock

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: SoldinWorldBlock
          path: target/SoldinWorldBlock-1.0.jar
